spring.application.name=notification-service
server.port=8085

# Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Firebase configuration
# Put your serviceAccountKey.json at src/main/resources/
app.firebase.config-file=serviceAccountKey.json
