spring.application.name=payment-service
server.port=8086

# Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Razorpay credentials (USE ENVIRONMENT VARIABLES IN PRODUCTION)
razorpay.key.id=${RAZORPAY_KEY:rzp_test_placeholder}
razorpay.key.secret=${RAZORPAY_SECRET:your_secret_placeholder}
