package com.javaCoffee.product_service.model;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Product Entity representing a record in the "product" collection in MongoDB.
 */
@Document(value = "product")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product {
    /** Unique identifier for the product, automatically generated by MongoDB */
    @Id
    private String id;

    /** Name of the product */
    private String name;

    /** Detailed description of the product */
    private String description;

    /** Price of the product */
    private Double price;
}
